#!/usr/bin/env python3
"""Generate INVENTORY.md — the AUTHORITATIVE, anti-hallucination ground truth.

Reads the real registries and emits one Markdown doc listing the ONLY valid
training tasks and viewer robots, so a local model never invents ones that
don't exist. Stdlib only.

    python3 gen_inventory.py            # write INVENTORY.md next to this script
    python3 gen_inventory.py --check    # exit 1 if INVENTORY.md is stale
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CLAW = os.environ.get("NEWTON_CLAW_DIR", os.path.dirname(os.path.dirname(HERE)))
OUT = os.path.join(HERE, "INVENTORY.md")


def build():
    tasks = json.load(open(os.path.join(CLAW, "newton_lab", "tasks_registry.json")))["environments"]
    robots = json.load(open(os.path.join(CLAW, "newton_sim", "robots.json")))["robots"]
    L = ["# newton-claw — INVENTORY (authoritative ground truth)", "",
         "> GENERATED by `skills/inventory/gen_inventory.py` from `newton_lab/tasks_registry.json`",
         "> and `newton_sim/robots.json`. **Do not edit by hand.** This is the ONLY valid list.", "",
         f"## Training / inference tasks ({len(tasks)})",
         "Exact ids for `claw train|play|eval --task <id>`. No others exist.", "",
         "| Task id | Robot | Category | Control | Pretrained policy |", "|---|---|---|---|---|"]
    for t in tasks:
        L.append(f"| `{t['id']}` | {t['robot']} | {t['category']} | {t['control']} | {'yes' if t.get('pretrained') else 'no'} |")
    L += ["", f"## Robots for the viewer ({len(robots)})",
          "Exact names for `claw open --robot <name>`. No others exist.", "",
          "| Name | Category | What you see |", "|---|---|---|"]
    for r in robots:
        L.append(f"| `{r['name']}` | {r['category']} | {r['description']} |")
    L += ["", "## Rules",
          "- If a robot or task is not listed above, it is NOT available — say so; never substitute.",
          "- There are no warehouse/office/hospital scenes and no Isaac Sim on this system: physics is Newton.",
          "- Simulator: Newton (MuJoCo-Warp solver). Trainer: rsl_rl PPO. Device: NVIDIA Jetson Thor.", ""]
    return "\n".join(L)


if __name__ == "__main__":
    text = build()
    if "--check" in sys.argv:
        sys.exit(0 if os.path.exists(OUT) and open(OUT).read() == text else 1)
    open(OUT, "w").write(text)
    print(f"wrote {OUT}")
